apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - ./configuration/varReference.yml
configMapGenerator:
  - name: config
    literals:
      - PLUGIN_NAME=ideaSearch
      - ENVIRONMENT=develop
      - COMMIT_HASH=c44a696be5bc38738084647f8c6ed6c19b24317b
bases:
  - ../../bases/atlassian-plugin-dev
  - ../../bases/config
# The variables defined below can be referenced in resources using the syntax $(VARIABLE)
vars:
  - name: environment
    fieldref:
      fieldpath: data.ENVIRONMENT
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: config
  - name: commitHash
    fieldref:
      fieldpath: data.COMMIT_HASH
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: config
  - name: pluginName
    fieldref:
      fieldpath: data.PLUGIN_NAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: config
