---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

# namePrefix: ideaSearch-

commonLabels:
  environment: qa

configurations:
- ./configuration/varReference.yml

configMapGenerator:
- name: config
  literals:
  - PLUGIN_NAME=ideaSearch
  - ENVIRONMENT=$(environment)
  - COMMIT_HASH=4e786d1e8cf536aa085520e4f8976d614fcb3b80

bases:
  - ../../bases/atlassian-plugin
  - ../../bases/config


# The variables defined below can be referenced in resources using the syntax $(VARIABLE)
vars:
- name: environment
  fieldref:
    fieldpath: metadata.labels.environment
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: config
- name: commitHash
  fieldref:
    fieldpath: data.COMMIT_HASH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: config
- name: pluginName
  fieldref:
    fieldpath: data.PLUGIN_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: config
