apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - ./configuration/varReference.yml
configMapGenerator:
  - name: config
    literals:
      - PLUGIN_NAME=ideaSearch
      - ENVIRONMENT=qa
      - COMMIT_HASH=86618fcab7c7e28dca9a9ab9289a3d668ea09679
bases:
  - ../../bases/atlassian-plugin-qa
  - ../../bases/config
# The variables defined below can be referenced in resources using the syntax $(VARIABLE)
vars:
  - name: environment
    fieldref:
      fieldpath: data.ENVIRONMENT
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: config
  - name: commitHash
    fieldref:
      fieldpath: data.COMMIT_HASH
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: config
  - name: pluginName
    fieldref:
      fieldpath: data.PLUGIN_NAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: config
