apiVersion: v1
kind: Service
metadata:
  name: plugin
  labels:
    app: plugin
spec:
  selector:
    app: "$(pluginName)-plugin"
    environment: $(environment)
  type: NodePort
  ports:
    - name: http
      port: 1990
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    environment: $(environment)
  name: plugin
  labels:
    app: "$(pluginName)-plugin"
    commitHash: "test"
spec:
  replicas: 1
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app: "$(pluginName)-plugin"
  template:
    metadata:
      labels:
        app: "$(pluginName)-plugin"
        environment: $(environment)
    spec:
      initContainers:
        - image: alpine/git
          name: git
          imagePullPolicy: IfNotPresent
          args:
            - clone
            - --branch 
            - $(environment)
            - https://github.com/agiledigital-labs/confluence-plugin-idea-search.git
            - /home/runner/artifacts


          volumeMounts:
            - name: artifacts
              mountPath: /home/runner/artifacts

      containers:
        - image: maven:3-openjdk-8
          name: "plugin"
          tty: true
          stdin: true
          imagePullPolicy: IfNotPresent
          env:
          - name: COMMIT_HASH
            value: $(commitHash)
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash

              if [ ! -d "/opt/atlassian-plugin-sdk/bin" ]; then
                echo "You need to add the atlassian sdk to the PV"
                echo "Use kubectl cp atlassian-plugin-sdk plugin-hash:/opt/"
                sleep 180
              fi


              export PATH=$PATH:/opt/atlassian-plugin-sdk/bin

              cd /home/runner/artifacts

              atlas-version

              atlas-mvn package
              
              atlas-run --context-path ROOT


              
          ports:
            - containerPort: 1990
              name: http
            - containerPort: 34883
              name: rmi
            - containerPort: 8009
              name: ajp
            - containerPort: 5990
              name: test
          volumeMounts:
          - mountPath: /opt/atlassian-plugin-sdk
            name: atlassian-plugin-sdk
          - mountPath: /root/.m2
            name: maven-cache-volume
          - name: artifacts
            mountPath: /home/runner/artifacts
      volumes:
        - name: atlassian-plugin-sdk
          persistentVolumeClaim:
            claimName: atlassian-sdk-volume
        - name: maven-cache-volume
          persistentVolumeClaim:
            claimName: maven-cache-volume
        - name: artifacts
          emptyDir: {}

