apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlassian-sdk-volume
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache-volume
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
